"""rename department

Revision ID: 73a6a0676649
Revises: 7eebf4c4664e
Create Date: 2024-06-28 13:00:55.083058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a6a0676649'
down_revision = '7eebf4c4664e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.rename_table('departments', 'department')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
