"""rename address

Revision ID: 937c28c3d7ae
Revises: 73a6a0676649
Create Date: 2024-06-28 13:13:21.456310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937c28c3d7ae'
down_revision = '73a6a0676649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'address',  new_column_name='location')# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'location',  new_column_name='address')
    # ### end Alembic commands ###
